import { useState,type FormEvent } from "react";
import { useAuth } from "../auth/AuthProvider";
import { Badge,ErrorState,Field,Loading,Modal,PageHeader,ReauthFields,Table } from "../components/Ui";
import { adminApi } from "../lib/api";
import { dateTime,roleLabel } from "../lib/format";
import { reauthenticateAdmin } from "../lib/reauth";
import { useAdminData } from "../lib/useAdminData";

type PlatformAdmin={id:string;user_id:string;role:string;status:string;first_name?:string;last_name?:string;email:string;mfa_required:boolean;last_login_at?:string;last_activity_at?:string;created_at:string};
export function AdminsPage(){
 const {admin}=useAuth(),{data,loading,error,reload}=useAdminData<{items:PlatformAdmin[]}>("admins.list"),[open,setOpen]=useState(false),[message,setMessage]=useState("");
 async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget),button=event.currentTarget.querySelector<HTMLButtonElement>('button[type="submit"]');if(button)button.disabled=true;setMessage("");try{await reauthenticateAdmin(admin!.email,String(values.get("password")||""),String(values.get("totp")||""));await adminApi("admins.invite",{email:values.get("email"),firstName:values.get("first_name"),lastName:values.get("last_name"),role:values.get("role"),reason:values.get("reason")});setOpen(false);await reload();}catch(reason){setMessage(reason instanceof Error?reason.message:"Invitation impossible");if(button?.isConnected)button.disabled=false;}}
 return <><PageHeader eyebrow="Accès internes Piloz" title="Équipe administrative" description="Ces comptes sont indépendants des entreprises clientes et le MFA reste obligatoire." actions={admin?.permissions.includes("admin.write")&&<button className="primary-button" onClick={()=>setOpen(true)}>Inviter un administrateur</button>}/>{loading?<Loading/>:error?<ErrorState message={error}/>:<Table><thead><tr><th>Administrateur</th><th>Rôle</th><th>Statut</th><th>MFA</th><th>Dernière connexion</th><th>Dernière activité</th><th>Création</th></tr></thead><tbody>{data?.items.map(item=><tr key={item.id}><td><b>{[item.first_name,item.last_name].filter(Boolean).join(" ")||item.email}</b><small>{item.email}</small></td><td>{roleLabel(item.role)}</td><td><Badge tone={item.status==="active"?"positive":"danger"}>{item.status}</Badge></td><td><Badge tone={item.mfa_required?"positive":"danger"}>{item.mfa_required?"Obligatoire":"Invalide"}</Badge></td><td>{dateTime(item.last_login_at)}</td><td>{dateTime(item.last_activity_at)}</td><td>{dateTime(item.created_at)}</td></tr>)}</tbody></Table>}{open&&<Modal title="Inviter un administrateur de plateforme" description="Seul un super administrateur peut effectuer cette opération." onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={invite}><div className="form-grid"><Field label="Prénom"><input name="first_name" required/></Field><Field label="Nom"><input name="last_name" required/></Field><Field label="E-mail"><input name="email" type="email" required/></Field><Field label="Rôle"><select name="role"><option value="support_admin">Support</option><option value="billing_admin">Facturation</option><option value="compliance_admin">Conformité</option><option value="read_only_admin">Lecture seule</option><option value="super_admin">Super administrateur</option></select></Field></div><Field label="Motif obligatoire"><textarea name="reason" required/></Field><ReauthFields/>{message&&<p className="form-message">{message}</p>}<footer><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button type="submit" className="primary-button">Envoyer l’invitation</button></footer></form></Modal>}</>;
}
