import { useEffect,useState,type FormEvent } from "react";
import { ShieldCheck } from "lucide-react";
import { supabase } from "../lib/supabase";
import { useAuth } from "./AuthProvider";

export function Login(){
 const {session,admin,needsMfa,error,refresh,signOut}=useAuth();
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setMessage("");const {error:loginError}=await supabase.auth.signInWithPassword({email:email.trim(),password});setPassword("");if(loginError)setMessage("Connexion impossible. Vérifiez vos informations et réessayez.");else await refresh();setBusy(false);}
 async function forgot(){if(!email.trim())return setMessage("Saisissez votre adresse e-mail.");setBusy(true);const {error:resetError}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${location.origin}/settings`});setMessage(resetError?"La demande n’a pas pu être envoyée.":"Si ce compte existe, un message de réinitialisation a été envoyé.");setBusy(false);}
 if(session&&admin&&needsMfa)return <MfaGate onVerified={refresh}/>;
 return <main className="auth-page"><section className="auth-card"><img src="/piloz-logo.png" alt="Piloz"/><div className="auth-heading"><span><ShieldCheck size={18}/> Espace sécurisé</span><h1>Administration Piloz</h1><p>Accès réservé à l’équipe Piloz.</p></div>{error&&session?<div className="auth-denied"><p>{error}</p><button onClick={()=>void signOut()}>Utiliser un autre compte</button></div>:<form onSubmit={submit}><label>Adresse e-mail<input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Mot de passe<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{message&&<p className="form-message">{message}</p>}<button className="primary" disabled={busy}>{busy?"Vérification…":"Se connecter"}</button><button type="button" className="link" onClick={()=>void forgot()} disabled={busy}>Mot de passe oublié</button></form>}<small>Aucune inscription publique. MFA obligatoire.</small></section></main>;
}

function MfaGate({onVerified}:{onVerified:()=>Promise<void>}){
 const [factorId,setFactorId]=useState(""),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{void (async()=>{const {data,error}=await supabase.auth.mfa.listFactors();if(error){setMessage("Impossible de charger le second facteur.");setBusy(false);return;}const verified=data.totp.find(factor=>factor.status==="verified");if(verified){setFactorId(verified.id);setBusy(false);return;}const {data:enrollment,error:enrollError}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:"Piloz Admin"});if(enrollError){setMessage("L’activation MFA a échoué.");setBusy(false);return;}setFactorId(enrollment.id);setQr(enrollment.totp.qr_code);setSecret(enrollment.totp.secret);setBusy(false);})();},[]);
 async function verify(event:FormEvent){event.preventDefault();if(busy||code.length<6)return;setBusy(true);setMessage("");const {error}=await supabase.auth.mfa.challengeAndVerify({factorId,code:code.trim()});if(error){setMessage("Code incorrect ou expiré.");setCode("");setBusy(false);return;}await supabase.auth.refreshSession();await onVerified();setBusy(false);}
 return <main className="auth-page"><section className="auth-card mfa-card"><img src="/piloz-logo.png" alt="Piloz"/><div className="auth-heading"><span><ShieldCheck size={18}/> Protection obligatoire</span><h1>Authentification multifacteur</h1><p>{qr?"Scannez le QR code avec votre application d’authentification.":"Saisissez le code de votre application d’authentification."}</p></div>{qr&&<><img className="mfa-qr" src={qr} alt="QR code MFA"/><code className="mfa-secret">{secret}</code></>}<form onSubmit={verify}><label>Code à 6 chiffres<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,""))} required/></label>{message&&<p className="form-message">{message}</p>}<button className="primary" disabled={busy||code.length!==6}>{busy?"Vérification…":"Vérifier et continuer"}</button></form></section></main>;
}
